---
title: "Birth-Death Bayes Filter"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(expm)
```

## Torben's Matlab programme translated to R

```{r matlab}
# Parameters
# Switch for using HS parameters etc to compare with he's results
HS = 0
# TK test parameters
N = 300000; n = 10000; gamma = 1/3.4; R= 1.2;
MaxI = 100; NumDays = 4*7; IniMean = 12; UseMeas = 1; fig = 1;
TimeIntervention = Inf;
n = matrix(1, nrow = NumDays, ncol =1)*n;                   # Test size at day 1:NumDays
IniProb = 3;

# HS test parameters
if (HS){
  Pp=1.5e-2; #CoVid19 frequency among tests
  Ns=4*350000; #Approximate number of samples from mid Aug to mid Sept
  p=12/Ns; #mean estimate of cluster5 probability
  V=p*(1-p)/Ns; #variance of estimate of cluster5 probability
  Ninit=ceiling(p*6e6); #mean estimate of number of Cluster5 among population
  Nlow=ceiling(Ninit-2*sqrt(V)*6e6); #low limit
  Nhigh=ceiling(Ninit+2*sqrt(V)*6e6); #high limit
  N= 6e6*Pp; gamma= 1/5; R= 1.2;
  MaxI= 85; NumDays= 7*20; IniMean= 12; UseMeas= 1; fig= 1;
  MaxI= 85; NumDays= 60;   IniMean= 12; UseMeas= 1; fig= 1;
  TimeIntervention= 7*4; n1= round(1500/7); n2= round(3500/7); 
  n= matrix( 1, nrow = NumDays, ncol = 1)*n1;
  n[TimeIntervention:nrow(n),] = n2;
  IniProb= 2;
}

# Definitions etc.
beta = R*gamma; #Birth rate
# Construct Q
Q1 = matrix(0, MaxI, MaxI)
delta = row(Q1) - col(Q1)
Q1[delta == 1] <- (1:(MaxI-1))*gamma
Q1[delta == -1] <- (0:(MaxI-2))*beta
diag(Q1) <- -1*apply(Q1,1,sum)
EQ1 = expm(Q1)

if (HS){
  Q2 = matrix(0, MaxI+1, MaxI+1)
  delta = row(Q2) - col(Q2)
  Q2[delta == 1] <- (1:(MaxI))*gamma*2
  Q2[delta == -1] <- (0:(MaxI-1))*beta/2
  diag(Q2) <- -1*apply(Q2,1,sum)
  EQ2 = expm(Q2)
}  

# Measurements
Y = matrix(0, nrow = NumDays, ncol = 1); # Assume no Cluster5
Y[20,1]= 0*1;                            # Include a measurements of Cluster5
if (!UseMeas){
  Y= Y*NaN;
}

# Initial probability for states
P = matrix(0, nrow = MaxI, ncol = 1);
switch( IniProb,                      
        P[IniMean,1] <- 1,                     # Kronecker delta
        P[Nlow:Nhigh] <- 1/(Nhigh-Nlow+1),     # Uniform
        P[,1] <- dpois( 1:(MaxI), IniMean)       # Poisson
)
PP = matrix(0, nrow = MaxI, ncol = NumDays); # nstates x ndays container, holing day by day state aposteriori probabilities.

for( i in 1:NumDays){
  # Measurement update
  if (!is.nan(Y[i])){ # If there is a measurement
    P = P*dbinom(Y[i]*as.vector(matrix(1,MaxI,1)),
                   as.vector(n[i]*matrix(1,MaxI,1)),
                   (1:(MaxI)-1)/N);
    P= P/sum(P);
  }
  PP[,i] = P;                # PP does not include the initial PDF
                             # Time update;
  if(i<TimeIntervention){
    EQ = EQ1}else{
    EQ = EQ2}
  
  P= t(EQ)%*%P;
  # Correction for the error due to truncating number of infected to MaxI
  P = P/sum(P); 
}

plot(ts(PP),plot.type = "single", xlab = "#C5", ylab = "PDF")
```

