---
title: "collect_data"
author: "RFB"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ISOweek)
```

Read nextstrain data
```{r}
c5 <- read_tsv("../Data/nextstrain_groups_neherlab_ncov_DanishCluster_selected_metadata.tsv")

c5_week <- c5 %>% filter(Host == "Human") %>% 
  mutate(week = ISOweek(`Collection Data`)) %>% 
  select(Clade, week) %>% 
  group_by(week) %>% 
  summarize(cluster5 = n())

c5_week
```

Covid19 overvågningsdate fra SSI kan hentes fra: https://covid19.ssi.dk/overvagningsdata/download-fil-med-overvaagningdata 

Read epi data
```{r}
kom_cases <- read_csv2("../Data/Data-Epidemiologiske-Rapport-04022021-h1k6-v2/Municipality_cases_time_series.csv")
kom_test  <- read_csv2("../Data/Data-Epidemiologiske-Rapport-04022021-h1k6-v2/Municipality_tested_persons_time_series.csv")
kom_pos   <- read_csv2("../Data/Data-Epidemiologiske-Rapport-04022021-h1k6-v2/Municipality_test_pos.csv")

reg_test  <- read_csv2("../Data/Data-Epidemiologiske-Rapport-04022021-h1k6-v2/Test_regioner.csv")
```

Read genomic surveillance data from covid19genomics.dk 
```{r}
seq_data <- read_tsv("../Data/covid19genomicsdk_04_02_2021.tsv")
rn_seq   <- data.frame("week" = seq_data$Week,
                       "sequenced" = sapply(str_split(seq_data$Nordjylland, "/"),
                                             function(x) x[[1]]))
```


Nordjyske kommuner
```{r}
rn_kom <- c("Hjørring", "Brønderslev", "Frederikshavn", "Jammerbugt", "Læsø", "Mariagerfjord",
            "Morsø", "Rebild", "Thisted", "Vesthimmerlands", "Aalborg")
```

Summarize tests per week for RN
```{r}
rn_test_week <- kom_test %>% 
  select(PrDate_adjusted, all_of(rn_kom)) %>% 
  pivot_longer(cols = all_of(rn_kom)) %>% 
  mutate(week = ISOweek(PrDate_adjusted)) %>% 
  group_by(week) %>% 
  summarize(tests = sum(value))
```

Summarize cases per week for RN
```{r}
rn_case_week <- kom_cases %>% 
  select(date_sample, all_of(rn_kom)) %>% 
  pivot_longer(cols = all_of(rn_kom)) %>% 
  mutate(week = ISOweek(date_sample)) %>% 
  group_by(week) %>% 
  summarize(cases = sum(value))
```


Join data
```{r}
week_data <- rn_test_week %>% 
  left_join(rn_case_week, by = "week") %>%
  left_join(rn_seq, by = "week") %>% 
  left_join(c5_week, by = "week")
```

Dump data
```{r}
write_csv2(week_data, file = "../Data/rn_cluster5_data.csv")
```

```{r}
getwd()
```

